all:
  hosts:
    node1:
      ansible_host: <IP-address>
    node2:
      ansible_host: <IP-address>
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
  vars:
    ansible_connection: ssh
    ansible_user: <SSH_USER>
